# Generated by Django 4.1.1 on 2022-09-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='p_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
